spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://10.83.128.16:3306/ec_draw?tinyInt1isBit=false&useUnicode=true&characterEncoding=utf-8&autoReconnect=true&failOverReadOnly=false&zeroDateTimeBehavior=convertToNull
    username: ec_draw
    password: ec_draw
    hikari:
      connection-test-query: SELECT 1 FROM DUAL
      minimum-idle: 3
      maximum-pool-size: 24
      pool-name: ${spring.application.name}-CP
      idle-timeout: 10000
      cachePrepStmts: true
      prepStmtCacheSize: 250
      prepStmtCacheSqlLimit: 2048
      leakDetectionThreshold: 2000

  thymeleaf:
    cache: false

  redis:
    host: 10.83.10.241
    port: 6379
    password: Welcome1
    database: 9
    timeout: 30000
    pool:
      max-active: 20
      max-idle: 5

server:
  port: 8888

mybatis:
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 30
  mapperLocations: classpath*:mapper/*.xml



netty:
  #监听websocket连接的端口
  port: 11111
  #此处要用电脑的ip,不然手机访问会出现问题
  ws: ws://localhost:${netty.port}/ws
